version: "3.8"

services:
  backend:
    build: .
    container_name: skillspark-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - skillspark-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skillspark-backend.rule=Host(`api.yourdomain.com`)"
      - "traefik.http.routers.skillspark-backend.tls=true"
      - "traefik.http.services.skillspark-backend.loadbalancer.server.port=8001"

networks:
  skillspark-network:
    driver: bridge

volumes:
  logs:
    driver: local
